name: SupplySign
main: redsgreens.SupplySign.SupplySign
version: 1.21.1
author: michaelwj
commands:
  supplysign:
    description: 'Used to reload data and list available SupplySign kits' 
    usage: '/supplysign <reload | listkits> (Used to reload data and list available SupplySign kits)'
website: https://www.spigotmc.org/resources/supplysign.118325/
api-version: 1.21